sudo: required
services:
  - docker

before_install:
  - docker build -t mdrahman76/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mdrahman76/react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t mdrahman76/multi-client ./client
  - docker build -t mdrahman76/multi-nginx ./nginx
  - docker build -t mdrahman76/multi-server ./server
  - docker build -t mdrahman76/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mdrahman76/multi-client
  - docker push mdrahman76/multi-nginx
  - docker push mdrahman76/multi-server
  - docker push mdrahman76/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi_docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-396017732323
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY